In [279]:
import numpy as np

In [280]:
ten_fives=np.ones(10)*5
print(ten_fives)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [281]:
ten_to_fifty=np.arange(10,50)
print(ten_to_fifty)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [282]:
even_ten_to_fifty=np.arange(10,50,2)
print(even_ten_to_fifty)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48]


In [283]:
mat=np.arange(0,9).reshape(3,3)
print(mat)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [284]:
random_numbers = np.random.normal(0,1,25)
print(random_numbers)

[ 0.89503708 -0.90114615  2.3574538   1.26715473 -0.33018179 -0.04397289
  1.00030568 -0.67374528  1.07079512  0.64952744 -0.4355912  -0.77643541
  0.46456819  0.88584186  0.69445232  0.50269428 -0.12737754 -2.19176245
  0.65901567  0.76160038 -0.7866241  -0.63254412 -0.48793459  0.77311133
 -0.43683315]


In [285]:
cd1e_2=np.arange(0,1.01,0.01)
print(cd1e_2)

[0.   0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1  0.11 0.12 0.13
 0.14 0.15 0.16 0.17 0.18 0.19 0.2  0.21 0.22 0.23 0.24 0.25 0.26 0.27
 0.28 0.29 0.3  0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4  0.41
 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5  0.51 0.52 0.53 0.54 0.55
 0.56 0.57 0.58 0.59 0.6  0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69
 0.7  0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8  0.81 0.82 0.83
 0.84 0.85 0.86 0.87 0.88 0.89 0.9  0.91 0.92 0.93 0.94 0.95 0.96 0.97
 0.98 0.99 1.  ]


In [286]:
zero_to_one_20=np.arange(0,1.05,0.05)
print(zero_to_one_20)

[0.   0.05 0.1  0.15 0.2  0.25 0.3  0.35 0.4  0.45 0.5  0.55 0.6  0.65
 0.7  0.75 0.8  0.85 0.9  0.95 1.  ]


In [287]:
mat25=np.arange(1,26).reshape(5,5)
print(mat25)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [288]:
print(mat25[2:,1:])

[[12 13 14 15]
 [17 18 19 20]
 [22 23 24 25]]


In [289]:
print(mat25[0:3,1:2])

[[ 2]
 [ 7]
 [12]]


In [290]:
print(np.sum(mat25))

325


In [291]:
print(np.sum(mat25,axis=0))
print(np.sum(mat25,axis=1))

[55 60 65 70 75]
[ 15  40  65  90 115]
